@startuml YouViewContext
title Context iViews

iViews *--> "n" User
iViews *--> Video

User --> "0..n" Video
User ..> Comment
User *--> Playlist

Video *--> "1" Detail
Video *--> "1" Thumbnail
Video *--> "1" Audience
Video o--> "0..n" Comment
Video *--> "0..n" Tags
Video *--> Category
Video *--> Rating

Playlist o--> "0..n" Video

Audience <|-- Childish
Audience <|-- Adult

@enduml
