@startuml YouViewContext
title Context iViews

iViews *--> "0..n" User
iViews --> "0..n" Video
User *--> "0..n" Video
User ..> Comment
User *--> Playlist
Video *--> "1" Detail
Video *--> "1" Thumbnail
Video *--> "1" Audience
Video o--> "0..n" Comment

Playlist o--> "0..n" Video

@enduml
