@startuml UseCaseResumeView
title Use Case Resume View

state OUT_GAME
state INITIAL
state EXIT
state A as " "
state B as " "
state if <<choice>>

[*] --> OUT_GAME
OUT_GAME --> A : Player requests Resume  a New Game
A --> B : System request to Continuar
B --> if
    if --> EXIT : Player introduces No
    EXIT --> [*]
if --> INITIAL : Player introduces Yes
INITIAL --> [*]
@enduml