@startuml Types
title Types
namespace Types{
    enum ColorCode{
        +Red,
        +Green,
        +Yellow,
        +Blue,
        +Magenta,
        +Cyan,
        +Null
        +IsNull(ColorCode) : bool
        +GetInitial(ColorCode) : char
    }

    enum ErrorCode{
        +Duplicated,
        +WrongCharacters,
        +WrongLength,
        +Null
        +IsNull(ErrorCode) : bool
    }
}
@enduml