@startuml TicTacToeArchitectureDocumentView
package TicTacToe #DDDDDD { }
Package TicTacToe.ConsoleApp #DDDDDD { }
package TicTacToe.Models #DDDDDD { }
package TicTacToe.Utils #DDDDDD { }
package DotNet.Console #White{ }
package DotNet.Utils #White{ }

TicTacToe <.up. TicTacToe.ConsoleApp
TicTacToe .down.> TicTacToe.Models
TicTacToe.Models .down.> TicTacToe.Utils
TicTacToe.Models .down.> DotNet.Utils
TicTacToe.ConsoleApp .down.> TicTacToe.Models
TicTacToe.ConsoleApp .down.> TicTacToe.Utils
TicTacToe.ConsoleApp .down.> DotNet.Console
@enduml
