@startuml ViewUseCasePlay
title View Use Case Play

state IN_GAME

state if <<choice>>
state if2 <<choice>>
state if3 <<choice>>


[*] --> IN_GAME
IN_GAME --> A : System requests a combination
A --> if : Player enters a combination
if --> B
    if --> D : [error]
    note on link 
        Wrong colors
        Wrong lenght
    endnote
    D --> I : System displays errors
    I --> H 
B --> C : System displays results
C --> if2
    if2 --> H
if2 --> E : [WinnerResult]
E --> F : System displays winner message
F --> if3 : System resquest Resume
if3 --> H 
    H --> [*] : System allows Play
if3 --> [*]
@enduml