@startuml ViewUseCaseStart
title View Use Case start
state INITIAL
state IN_GAME
state start as " "
state started as " "
[*] --> INITIAL
INITIAL --> start : Player requests a new game
start --> started : system show a clear board
started --> IN_GAME : system ready to play
IN_GAME --> [*]
@enduml