@startuml StartUseCaseAnalysis
left to right direction
title Start Use Case Analysis

actor Player
boundary GameView
boundary StartView
boundary MessageView
boundary BoardView
boundary SetUpPlayerView

entity GameEntity
entity BoardEntity
entity TurnEntity
entity PlayerEntity
entity TokenEntity
entity Coordinate

Player -- GameView
GameView -- StartView

StartView -- MessageView
StartView -- BoardView
StartView -- SetUpPlayerView

SetUpPlayerView -- MessageView
SetUpPlayerView -- GameEntity

BoardView -- MessageView
BoardView -- GameEntity
BoardView .. Coordinate
BoardView .. TokenEntity

GameEntity -- BoardEntity
GameEntity -- TurnEntity

TurnEntity -- PlayerEntity
TurnEntity .. TokenEntity
PlayerEntity -- TokenEntity

BoardEntity --TokenEntity
BoardEntity .. Coordinate
@enduml

@startuml PlayUseCaseAnalysis
left to right direction
title Play Use Case Analysis

actor Player
boundary GameView
boundary PlayView
boundary PlayerView
boundary MessageView
boundary BoardView
boundary ErrorView
boundary TokenView

entity GameEntity
entity BoardEntity
entity TokenEntity
entity TurnEntity
entity PlayerEntity
entity ErrorEntity
entity CoordinateEntity

Player -- GameView
GameView -- PlayView

PlayView -- PlayerView
PlayView -- MessageView
PlayView -- BoardView
PlayView -- GameEntity

PlayerView -- MessageView
PlayerView -- ErrorView
PlayerView -- GameEntity
PlayView .. TokenEntity

BoardView -- MessageView
BoardView .. TokenView
BoardView .. CoordinateEntity

TokenView .. TokenEntity

ErrorView -- GameEntity
ErrorView .. ErrorEntity

GameEntity -- TurnEntity
TurnEntity -- PlayerEntity
PlayerEntity -- TokenEntity
PlayerEntity -- BoardEntity
PlayerEntity -- ErrorEntity

BoardEntity .. CoordinateEntity
BoardEntity -- TokenEntity
BoardView -- GameEntity

@enduml

@startuml ResumeUseCaseAnalysis
left to right direction
title Resume Use Case Analysis

actor Player
boundary GameView
boundary ResumeView
boundary YesNotDialog
boundary MessageView

entity GameEntity
entity BoardEntity
entity TokenEntity
entity CoordinateEntity

Player -- GameView
GameView -- ResumeView
ResumeView -- MessageView
ResumeView -- YesNotDialog
ResumeView -- GameEntity

YesNotDialog .. MessageView

GameEntity -- BoardEntity

BoardEntity -- TokenEntity
BoardEntity .. CoordinateEntity
@enduml


