@startuml ArchitectureDesign
title Architecture Design - Document/View
package ConnectFour{
    namespace Connect4 #Brown{}
    namespace ConsoleApp #SlateBlue{}
    namespace WindFormsApp #BlueViolet{}
    namespace Views #IndianRed{}
    namespace Models #GreenYellow{}
    namespace Types #CadetBlue{}
    namespace Utils #Yellow{}
    
    Connect4 ..> Models
    Connect4 ..> Views

    ConsoleApp ..> Connect4
    ConsoleApp ..> Models
    ConsoleApp ..> Views
    ConsoleApp ..> Types
    ConsoleApp ..> Utils
    
    WindFormsApp ..> Connect4
    WindFormsApp ..> Models
    WindFormsApp ..> Views
    WindFormsApp ..> Types
    WindFormsApp ..> Utils

    Views ..> Models
    Views ..> Types
    Views ..> Utils

    Models ..> Types
    Models ..> Utils

    Types ..> Utils
}
@enduml

@startuml Connect4Design
title Connect4 Design
package Connect4{
    abstract Connect4{
        +Connect4()
        #{abstract}CreateGameView(Game) : GameView
        #Play()
    }
    Connect4 <|-- ConsoleApp.ConnectFourView
    Connect4 <|-- WindFormApp.ConnectFourView
    Connect4 *--> Models.Game
    Connect4 *--> GameViews.GameView
}
@enduml

@startuml ConsoleApp
title ConsoleApp Design
package ConsoleApp #SlateBlue{
    class ConnectFour{
        ~Init()
        ~CreateGameView(Game) : ConsoleView
    }
    ConnectFour -up-|> Connect4.Connect4
    ConnectFour ..> ConsoleView
    ConnectFour *--> Models.Game

    class ConsoleView{
        ~ConsoleView(Game)
        ~Start()
        ~Play()
        ~IsResume() : boolean
    }
    ConsoleView -up-|> GViews.GameView
    ConsoleView --> Models.Game
    ConsoleView *--> StartView
    ConsoleView *--> PlayView
    ConsoleView *--> ResumeView

    class StartView{
        ~StartView(Game)
        ~Interact()
        -WriteLine(Title)
        -SetPlayer(Game)
        -WriteBoard(Game)
    }
    StartView --> Models.Game
    StartView ..> MessageView
    StartView ..> PlayerConfigurationView
    StartView ..> BoardView

    class PlayView{
        ~PlayView(Game)
        ~Interact()
        -GetCurrentTokne() : Token
        -WriteLine(TurnOf)
        -GetPlayerType() : PlayerType
        -CreatePlayerView(PlayerType) : PlayerView
        -IsWinner() : boolean
        -GetWinnerPlayer() : Token
        -WriteResult(isWinner, winnerPlayer)
    }
    PlayView --> Models.Game
    PlayView ..> Types.Token
    PlayView ..> GameViews.Message
    PlayView ..> Types.PlayerType
    PlayView ..> PlayerView
    PlayView ..> PlayerCreator

    class ResumeView{
        ~ResumeView(Game)
        ~Interact() : boolean
        -GetMessage(Message) : string
        -ReadAnswer(message) : char
        -IsAffirmative() : boolean
        -Reset()
    }
    ResumeView --> Models.Game
    ResumeView ..> GameViews.Message
    ResumeView ..> ConsoleIOs.YesNotDialog

    class MessageView{
        ~WriteLine(Message)
        ~WriteLine(Message, string)
        ~GetMessage(Message)
    }
    MessageView ..> GameViews.Message
    MessageView ..> ConsoleIOs.ConsoleIO

    class PlayerConfigurationView{
        ~SetPlayer(Game)
        -GetMessage(Message)
        -ReadNumOfPlayers(message) : int
        -GetErrorToSetUp(numOfPlayer) : Error
        -WriteLine(Error)
    }
    PlayerConfigurationView ..> Models.Game
    PlayerConfigurationView ..> ConsoleIOs.ConsoleIO
    PlayerConfigurationView ..> GameViews.Message
    PlayerConfigurationView ..> Types.Error
    PlayerConfigurationView ..> ErrorView

    class ErrorView{
        ~ErrorView(Error) : base(error)
        ~WriteLine(Error)
        ~WriteLine(colunm)
    }

    class BoardView{
        ~Write(Game)
        -WriteLine(HorizontalLine)
        -Write(VerticalLine)
        -GetToken(Coordinate)
        -Write(Token)
    }
    BoardView ..> Models.Game
    BoardView ..> GameViews.Message
    BoardView ..> MessageView
    BoardView ..> Types.Token
    BoardView ..> ConsoleIOs.ConsoleIO

    class PlayerCreator{
        -{static}instance : PlayerCreator
        -PlayerCreator()
        ~{static}GetInstance() : PlayerCreator
        ~CreatePlayerView(PlayerType) : PlayerView
    }
    PlayerCreator ..> PlayerView
    PlayerCreator ..> UserPlayer
    PlayerCreator ..> MachinePlayer

    abstract PlayerView{
        ~Drop(Game)
        #{abstract}ReadColunm() : int
        #GetErrorToDrop(colunm) : Error        
    }
    PlayerView <|-- UserPlayer
    PlayerView <|-- MachinePlayer
    PlayerView ..> Models.Game
    PlayerView ..> Types.Error


    class UserPlayer{
        ~UserPlayer(Game) : base(Game)
        ~ReadColunm() : int
        ~GetErrorToReadColunmOutOfRange(colunm) : Error
        ~GetErrorToDrop(colum) : Error
    }
    UserPlayer ..> ConsoleIOs.ConsoleIO

    class MachinePlayer{
        ~MachinePlayer(Game) : base(Game)
        ~ReadColunm() : int
    }
    MachinePlayer ..> Utils.Coordinate
}
@enduml

@startuml GameViewsDesign
title Game Views Design

package GameViews{
    abstract WithGameView{
        #gameView : Game
        +WithGameView(Game)
    }
    WithGameView --> Models.Game 

    abstract GameView{
        #{abstract}Start()
        #{abstract}Play()
        #{abstract}IsResume() : boolean
    }

    enum Message{
        +Titile,
        +HorizontalLine,
        +VerticalLine,
        +Turn,
        +NumOfPlayers,
        +Random,
        +EnterColunmToDrop,
        +InvalidColunm,
        +CompleteColunm,
        +PlayerWin,
        +PlayersTied,
        +Resume
        -{static}MESSAGES : string[]
        +GetMessage(Message) : string
    }

    abstract ErrorView{
        #{static}ERRORS : string[]
        +{abstract}WriteLine()
    }
    ErrorView --> Types.Error
}
@enduml

@startuml ModelsDesign
title Models Design

package Models{
    class Game{
        +Game()
        +Reset()
        +SetUp(numOfPlayers)
        +GetErrorToSetUpNumOfPlayer(players) : Error
        +GetToken(Coordinate) : Token
        +GetPlayerType() : PlayerType
        +GetCurrentTurn() : Token
        +Drop(colunm)
        +GetErrorToDrop(colunm) : Error   
        +Next()     
        +IsFinished() : boolean
        +IsWinner() : boolean
        +GetWinner() : Token
    }
    Game *--> Board
    Game *--> Turn
    Game *--> "2" Player
    Game ..> Types.PlayerType
    Game ..> Types.Token
    Game ..> Types.Error
    Game ..> Utils.Coordinate

    class Board{
        -tokens : Token[,]
        -lastDrop : Coordinate
        ~Board()
        ~Reset()
        ~Drop(colunm, Token)
        -GetLastDrop(colunm) : Coordinate
        -IsEmpty(Coordinate) : boolean
        -IsOccupied(Coordinate, Token) : boolean
        ~GetToken(Coordinate) : Token
        ~IsComplete(colunm) : boolean
        ~IsFinished() : boolean
        ~IsComplete() : boolean
        ~IsWinner() : boolean
        -IsCoonectFour(Line) : boolean
    }
    Board *--> "6x7" Types.Token
    Board ..> Utils.Coordinate
    Board ..> Utils.Line
    Board ..> Utils.Direction

    class Turn{
        ~{static}MAX_PLAYERS = 2
        ~{static}MIN_PLAYERS = 0
        -current : int
        ~Turn(Player[])
        ~Next()
        -Change()
        ~GetErrorToSetUpNumOfPlayer(players) : Error
        ~GetCurrentPlayer() : Player
        ~GetLastPlayer() : Player
    }
    Turn --> "2" Player
    Turn ..> Types.Error

    class Player{
        ~Player(Token, Board, PlayerType)
        ~Drop(Token)
        ~GetErrorToDrop(colunm) : Error
        ~GetToken() : Token
        ~GetPlayerType() : PlayerType
    }
    Player --> Board
    Player --> Types.Token
    Player --> Types.PlayerType
    Player ..> Types.Error
}
@enduml

@startuml TypesDesign
title Types Design
package Types{
    enum Token{
        +X,
        +O,
        +Null,
        +IsNull(Token) : boolean
        +GetToString(Token) : string
    }

    enum Error{
        +TheColunmIsComplete,
        +TheColunmIsOutOfRang,
        +PlayerIsOutOfRange,
        +Null,
        +IsNull(Error) : boolean
    }

    enum PlayerType{
        +UserPlayer
        +MachinePlayer
    }
}
@enduml

@startuml UtilsDesign
title Utils Design
package Utils{
    class Coordinate{
        +{static}ROWS = 6
        +{static}COLUNM = 7
        -row : int
        -colunm : int
        +Coordinate(row, colunm)
        +IsIncluded() : boolean
        +IsValid(value) : boolean
        +Equals(Coordinate) : boolean
        +Shifted(Coordinate) : Coordinate
    }
    Coordinate ..> ClosedInterval

    class ClosedInterval{
        -min : int
        -max : int
        ~ClosedInterval(min, max)
        ~IsIncluded(value) : boolean
    }

    class Direction{
        +{static}North : Direction(1, 0)
        +{static}NorthEast : Direction(1, 1)
        +{static}East : Direction(0, 1)
        +{static}SouthEast : Direction(-1, 1)
        +{static}South : Direction(-1, 0)
        +{static}SouthWest : Direction(-1, -1)
        +{static}West : Direction(0, -1)
        +{static}NorthWest : Direction(1, -1)
        +{static}Null : Direction(0, 0)

        -coordinate : Coordinate
        +Direction(row, colunm)
        +GetCoordinate() : Coordinate
        +GetOppositeDirection() : Direction
        +GetDirections() : List<Direction>
    }
    Direction *--> Coordinate


    class Line{
        +{static}LENGTH = 4
        -coordinates : Coordinate[]
        -coordinate : Coordinate
        -oppositeDirection : Direction
        +Line(Coordinate)
        +GetCoordinates : Coordinate[]
        +SetDirection()
        +Shift()
    }
    Line --> Coordinate : coordinate
    Line *--> "4" Coordinate : coordinates
    Line --> Direction

}
@enduml