@startuml ArchitectureDocumentViewBasic
title Architecture Document/View With Factory Method

namespace Mastermind #GreenYellow { }
namespace ConsoleApp #LightBlue { }
namespace GraphicsApp #SlateBlue {}
namespace Views #CadetBlue {}
namespace Models #RoyalBlue { }
namespace Types #Yellow { }
namespace Net.IO #DDDDDD { }
namespace Net.Utils #DDDDDD { }
namespace Net.Graphics #DDDDDD{}

Mastermind .down.> Models
Mastermind .down.> Views

ConsoleApp .down.> Mastermind
ConsoleApp .down.> Models
ConsoleApp .down.> Views
ConsoleApp .down.> Types
ConsoleApp ..> Net.IO

GraphicsApp .down.> Mastermind
GraphicsApp .down.> Models
GraphicsApp .down.> Views
GraphicsApp .down.> Types
GraphicsApp .down.> Net.Graphics

Views .down.> Models

Models .down.> Types
Models ..> Net.Utils

Types ..> Net.Utils

@enduml


Mastermind .down.> ConsoleApp
Mastermind .down.> GraphicsApp