@startuml UseCaseStartView
title Use Case Start View

state IN_GAME
state A as " "
state B as " "
state C as " "

[*] --> IN_GAME
IN_GAME --> A : Player requests to Start a New Game
A --> B : System displays Secrect Combination and attempts in 0
B --> C : System allows Play
C --> [*]
@enduml