@startuml UseCasePlayView
title Use Case Play View

state IN_GAME
state INITIAL
state A as " "
state B as " "
state C as " "
state D as " "
state E as " "
state G as " "

state if1 <<choice>>
state if2 <<choice>>
state if3 <<choice>>

[*] --> IN_GAME
IN_GAME --> A : System requests a Proposed Combination
A --> B : Player introduces a Combination
    B --> if1 : [error]    
    note on link
        Wrong color(s)
        Wrong Lenght of color
        There are duplicated color
    endnote
    if1 --> C : System displays error message
    C --> D : System allows Play
    D --> [*]
if1 --> E
E --> if2 : System displays Results
    if2 --> C
if2 --> G : [IsFinished]
G --> if3 : Resume
    if3 --> OUT_GAME
    OUT_GAME --> [*]
if3 --> INITIAL : [Continue]
INITIAL -->  [*]

@enduml