@startuml UseCaseContext
state INITIAL
state IN_GAME
state OUT_GAME
state EXIT
state if_finished <<choice>>
state if_resumed <<choice>>


[*] --> INITIAL
INITIAL --> IN_GAME: Start
IN_GAME --> if_finished: Play
if_finished --> IN_GAME
if_finished --> OUT_GAME: [finished]
OUT_GAME --> if_resumed: Resume
if_resumed --> INITIAL: [continued]
if_resumed --> EXIT
EXIT --> [*]
@enduml


@startuml ViewUseCaseStart
state INITIAL
state IN_GAME
state start as " "
state started as " "
[*] --> INITIAL
INITIAL --> start: Player requests a new game   
start --> started: system show empty board
started --> IN_GAME : system ready to play 
IN_GAME -->[*]
@enduml

@startuml ViewUseCasePlay
state IN_GAME
state A as " "
state B as " "
state C as " "
state D as " "
state E as " "
state F as " "
state G as " "
state H as " "
state K as " "
state L as " "
state M as " "
state N as " "
state I as " "

state if <<choice>>
state if1 <<choice>>
state if2 <<choice>>
state if3 <<choice>>
state if4 <<choice>>

[*] --> IN_GAME
IN_GAME --> if: current player request Play
if --> A: [token on board < 3]
    if --> F: system request coordinate to move
    F --> G: current player enter coordinate
    G --> if2: system displays updated board--
    if2 --> H: system request coordinate to put
        if2 --> K: [error!!]
        note on link
            coordinate is not valid
            square is not empty
            player is not owner of token on square
        end note
        K --> L: system show errors
        L --> [*]: systeme allows to continue the game
    H --> if3: current player enter coordinate
    if3 --> M
        M --> if1: [error!]
    if3 --> C
    
A --> B: system request coordinate to put 
B --> C : current player enter coordinate
C --> if1
    if1 --> N: [error]
    note on link
        coordinate is not valid
        square is not empty
    end note
    N --> L: system show errors!!!
if1 --> D
D --> if4: system displays updated board
    if4 --> L
if4 --> E: [is winner]
E --> I: system displays winner message
I --> [*]: system asks Resume
@enduml 

@startuml ViewUseCaseResume
state OUT_GAME
state INITIAL
state EXIT
state A as " "
state B as " "
state if <<choice>>

[*] --> OUT_GAME
OUT_GAME --> A: system request Resume
A --> if
if --> INITIAL: player answer yes
    INITIAL --> [*]
if --> EXIT: player answer no
    EXIT --> [*]
@enduml