@startuml InitialState
 title Initial State

 object TicTacToe
 object Board
 object X
 object O

 TicTacToe --> Board

 object "Square" as o1
 object "Square" as o2
 object "Square" as o3
 object "Square" as o4
 object "Square" as o5
 object "Square" as o6
 object "Square" as o7
 object "Square" as o8
 object "Square" as o9

 object "Coordinate" as c1 {
    row = 0
    column = 0
 }
 object "Coordinate" as c2{
    row = 0
    column = 1
    
 }
 object "Coordinate" as c3{
    row = 0
    column = 2
 }
 object "Coordinate" as c4{
    row = 1
    column = 0
 }
 object "Coordinate" as c5{
    row = 1
    column = 1
 }
 object "Coordinate" as c6{
    row = 1
    column = 2
 }
 object "Coordinate" as c7{
    row = 2
    column = 0
 }
 object "Coordinate" as c8{
    row = 2
    column = 1
 }
 object "Coordinate" as c9{
    row = 2
    column = 2
 }

Board --> o1
Board --> o2
Board --> o3
Board --> o4
Board --> o5
Board --> o6
Board --> o7
Board --> o8
Board --> o9

o1 --> c1
o2 --> c2
o3 --> c3
o4 --> c4
o5 --> c5
o6 --> c6
o7 --> c7
o8 --> c8
o9 --> c9


 object "Piece" as p1
 object "Piece" as p2
 object "Piece" as p3
 object "Piece" as p4
 object "Piece" as p5

 p1 --> X
 p2 --> X
 p3 --> X
 p4 --> O
 p5 --> O

c1 --> p1
c2 --> p4

c5 --> p2
c6 --> p5

c9 --> p3



@enduml