@startuml Vocabulary
title Vocabulary

Connect4 *-down-> "1" Board
Connect4 *-down-> "1" Turn
Connect4 *-down-> "2" Player

Turn -down-> "2" Player

Player -down-> "1" Board
Player o-down-> "0..21" Token
Player *-down-> "1" Color
Player o-down-> Goal

Goal .down.> "4" Square
Goal ..> "4" Insertion
Tie ..> "42" Square

Insertion .down.> Token
Insertion .down.> Square : target
Insertion .down.> Coordinate

Token -down-> Coordinate
Token *-down-> Color

Color <|-down- Red
Color <|-down- Yellow

Board *-down-> "6x7" Square
Square *-down-> "1" Coordinate
Square o-down-> "0..42" Token

Goal <|-down- InHorizontal
Goal <|-down- InVertical
Goal <|-down- InMainDiagonal
Goal <|-down- InInverseDiagonal
Goal <|-down- Tie
@enduml