@startuml ArchitectureDocumentViewBasic
title Architecture Document/View With Out Factory Method

namespace Mastermind #DDDDDD {
    namespace Mastermind.ConsoleApp #LightBlue { }
    namespace Mastermind.GraphicsApp #SlateBlue {}
    namespace Mastermind.Views #CadetBlue {}
    namespace Mastermind.Models #RoyalBlue { }
    namespace Mastermind.Types #Yellow { }
    namespace Net.IO #DDDDDD { }
    namespace Net.Utils #DDDDDD { }
    namespace Net.Graphics #DDDDDD{}


    Mastermind.ConsoleApp .down.> Mastermind.Models
    Mastermind.ConsoleApp .down.> Mastermind.Views
    Mastermind.ConsoleApp .down.> Mastermind.Types
    Mastermind.ConsoleApp ..> Net.IO

    Mastermind.GraphicsApp .down.> Mastermind.Models
    Mastermind.GraphicsApp .down.> Mastermind.Views
    Mastermind.GraphicsApp .down.> Mastermind.Types
    Mastermind.GraphicsApp .down.> Net.Graphics

    Mastermind.Views .down.> Mastermind.Models

    Mastermind.Models .down.> Mastermind.Types
    Mastermind.Models ..> Net.Utils

    Mastermind.Types ..> Net.Utils
 }
@enduml