@startuml TicTacToeDomainModelArchitecture
title Domain Model
package TicTacToe{    
    namespace TicTacToe.ConsoleApp{
        class TicTacToe{
            ~TicTacToe()
            ~Start()
            -PlayGame()
            -Resume() : bool
            -NewGame()
            ~{static} Main(string)
        }
        TicTacToe *--> "1" Turn
        TicTacToe *--> "2" Player
        TicTacToe *--> "1" Board
        TicTacToe ..> Message
        TicTacToe ..> MessageType            

        class Turn{
            ~{static} NUM_PLAYERS : int
            -current : int
            ~CurrentPlayer => current
            ~Last => Change()
            ~Turn(Player[])
            ~Reset()
            ~Next()
            -Change() : int
        }
        Turn *--> "2" Player
        Turn ..> "2" Token

        class Player{
            ~Token => Token
            ~Player(Token, Board)
            ~MakeMove()
            -PutToken()
            -ReadCoordinate(MessageType) : Coordinate
            ~GetErrorTypeToPut(Coordinate) : ErrorType.Empty
            -MoveToken()
            ~GetErrorTypeToMoveOrigin(Coordinate) : ErrorType.NotOwner
            ~GetErrorTypeToMoveTarget(Coordinate, Coordinate) : ErrorType.SameCoordinate
            ~Resume() : bool
        }
        Player ..> Token
        Player --> Board
        Player ..> Coordinate
        Player ..> Message
        Player ..> MessageType
        Player ..> Error
        Player ..> ErrorType
        Player ..> YesNotDialog

        class Board{
            ~Board()
            ~Reset()
            ~AreAllTokenOnBoard(Token) : bool
            ~PutToken(Coordinate, Token)
            ~GetErrorTypeToPut(Coordinate) : ErrorType.Empty
            ~IsOccupied(Coordinate, Token) : bool
            ~MoveToken(Coordinate, Coordinate)
            -IsEmpty(Coordinate) : bool
            -GetToken(Coordinate) : Token
            ~GetErrorTypeToMoveOrigin(Coordinate) : ErrorType.NotOwner
            ~GetErrorTypeToMoveTarget(Coordinate, Coordinate) : ErrorType.SameCoordinate
            ~IsTicTacToe(Token) : bool
            -GetDirections(Token) : List<Direction>
            -GetCoordinate(Tokent) : List<Coordinate>
            ~Write()
        }
        Board o--> "3x3" Token
        Board ..> Coordinate
        Board ..> Direction
        Board ..> Message
        Board ..> MessageType
        Board ..> Error
        Board ..> ErrorType
        Board ..> ConsoleIO

        class Coordinate{
            -[static] DIMENSION : int
            -{static} ROW : string
            -{static} COLUNM : string
            -row : int
            -colunm : int
            ~Row => row
            ~Colunm => colunm
            ~Coordinate(row, colunm)
            ~Read() : Coordinate
            ~IsValid() : bool
            ~Equals(Coordinate) : bool
            ~GetDirection(Coordinate) : Direction
            -InVertical() : bool
            -InHorizontal() : bool
            -InMainDiagonal() : bool
            -InInverseDiagonal() : bool
        }
        Coordinate ..> ClosedInterval
        Coordinate ..> ConsoleIO
        Coordinate ..> Direction
        Coordinate ..> Message
        Coordinate ..> MessageType

        class ClosedInterval{
            -min : int
            -max : int
            ~ClosedInterval(min, max)
            ~IsIncluide(value) : bool
        }
        class Message{
            -{static} MESSAGES : string[]
            ~Message(MessageType)
            ~Write(MessageType messageType)
            ~WriteLine()
            ~WriteLine(string player)
            WriteLine(MessageType)
        }
        Message --> MessageType
        Message ..> ConsoleIO

        enum MessageType{
            +TITLE,
            +HORIZONTAL_LINE,
            +VERTICAL_LINE,
            +ENTER_COORDINATE_TO_PUT,
            +COORDINATE_TO_PUT,
            +COORDINATE_TO_REMOVE,
            +COORDINATE_TO_MOVE,
            +WINNER,
            +RESUME
        }
        class YesNotDialog{
            ~YesNotDialog()
            ~Read(string)
            ~IsAffirmative() : bool
        }
        YesNotDialog ..> ConsoleIO

        enum Direction{
            +HORIZONAL,
            +VERTICAL,
            +MAIN_DIAGONAL,
            +iNVERSE_DIAGONAL,
            +NULL
        }

        enum Token{
            +X,
            +O,
            +NULL
        }
        
        class Error{
            -{static} ERRORS : string
            ~Error(ErrorType)
            ~WriteLine()
        }
        Error *--> ErrorType
        Error ..> ConsoleIO

        enum ErrorType{
            +IS_NOT_EMPTY,
            +NOT_OWNER,
            +SAME_COORDINATES,
            +WRONG_COORDINATES,
            +NULL
        }
    }
}

@enduml