@startuml InitialState
title Initial State
together {
    object ":Square" as Square11
    object ":Square" as Square12
    object ":Square" as Square13
    object ":Square" as Square14
    object ":Square" as Square15
    object ":Square" as Square16
    object ":Square" as Square17

    object ":Square" as Square21
    object ":Square" as Square22
    object ":Square" as Square23
    object ":Square" as Square24
    object ":Square" as Square25
    object ":Square" as Square26
    object ":Square" as Square27

    object ":Square" as Square31
    object ":Square" as Square32
    object ":Square" as Square33
    object ":Square" as Square34
    object ":Square" as Square35
    object ":Square" as Square36
    object ":Square" as Square37

    object ":Square" as Square41
    object ":Square" as Square42
    object ":Square" as Square43
    object ":Square" as Square44
    object ":Square" as Square45
    object ":Square" as Square46
    object ":Square" as Square47

    object ":Square" as Square51
    object ":Square" as Square52
    object ":Square" as Square53
    object ":Square" as Square54
    object ":Square" as Square55
    object ":Square" as Square56
    object ":Square" as Square57

    object ":Square" as Square61
    object ":Square" as Square62
    object ":Square" as Square63
    object ":Square" as Square64
    object ":Square" as Square65
    object ":Square" as Square66
    object ":Square" as Square67
}


object ":Coordinate" as Coordinate11 {
    row = 1
    column = 1
}
object ":Coordinate" as Coordinate12 {
    row = 1
    column = 2
}
object ":Coordinate" as Coordinate13 {
    row = 1
    column = 3
}
object ":Coordinate" as Coordinate14 {
    row = 1
    column = 4
}
object ":Coordinate" as Coordinate15 {
    row = 1
    column = 5
}
object ":Coordinate" as Coordinate16 {
    row = 1
    column = 6
}
object ":Coordinate" as Coordinate17 {
    row = 1
    column = 7
}


object ":Coordinate" as Coordinate21 {
    row = 2
    column = 1
}
object ":Coordinate" as Coordinate22 {
    row = 2
    column = 2
}
object ":Coordinate" as Coordinate23 {
    row = 2
    column = 3
}
object ":Coordinate" as Coordinate24 {
    row = 2
    column = 4
}
object ":Coordinate" as Coordinate25 {
    row = 2
    column = 5
}
object ":Coordinate" as Coordinate26 {
    row = 2
    column = 6
}
object ":Coordinate" as Coordinate27 {
    row = 2
    column = 7
}


object ":Coordinate" as Coordinate31 {
    row = 3
    column = 1
}
object ":Coordinate" as Coordinate32 {
    row = 3
    column = 2
}
object ":Coordinate" as Coordinate33 {
    row = 3
    column = 3
}
object ":Coordinate" as Coordinate34 {
    row = 3
    column = 4
}
object ":Coordinate" as Coordinate35 {
    row = 3
    column = 5
}
object ":Coordinate" as Coordinate36 {
    row = 3
    column = 6
}
object ":Coordinate" as Coordinate37 {
    row = 3
    column = 7
}


object ":Coordinate" as Coordinate41 {
    row = 4
    column = 1
}
object ":Coordinate" as Coordinate42 {
    row = 4
    column = 2
}
object ":Coordinate" as Coordinate43 {
    row = 4
    column = 3
}

object ":Coordinate" as Coordinate44 {
    row = 4
    column = 4
}
object ":Coordinate" as Coordinate45 {
    row = 4
    column = 5
}
object ":Coordinate" as Coordinate46 {
    row = 4
    column = 6
}
object ":Coordinate" as Coordinate47 {
    row = 4
    column = 7
}


object ":Coordinate" as Coordinate51 {
    row = 5
    column = 1
}
object ":Coordinate" as Coordinate52 {
    row = 5
    column = 2
}
object ":Coordinate" as Coordinate53 {
    row = 5
    column = 3
}
object ":Coordinate" as Coordinate54 {
    row = 5
    column = 4
}
object ":Coordinate" as Coordinate55 {
    row = 5
    column = 5
}
object ":Coordinate" as Coordinate56 {
    row = 5
    column = 6
}
object ":Coordinate" as Coordinate57 {
    row = 5
    column = 7
}



object ":Coordinate" as Coordinate61 {
    row = 6
    column = 1
}
object ":Coordinate" as Coordinate62 {
    row = 6
    column = 2
}
object ":Coordinate" as Coordinate63 {
    row = 6
    column = 3
}
object ":Coordinate" as Coordinate64 {
    row = 6
    column = 4
}
object ":Coordinate" as Coordinate65 {
    row = 6
    column = 5
}
object ":Coordinate" as Coordinate66 {
    row = 6
    column = 6
}
object ":Coordinate" as Coordinate67 {
    row = 6
    column = 7
}

object ":Connect4" as Connect4
object ":Board" as Board

Connect4 *-down-> Board

Board --> Square11
Board --> Square12
Board --> Square13
Board --> Square14
Board --> Square15
Board --> Square16
Board --> Square17

Board --> Square21
Board --> Square22
Board --> Square23
Board --> Square24
Board --> Square25
Board --> Square26
Board --> Square27

Board --> Square31
Board --> Square32
Board --> Square33
Board --> Square34
Board --> Square35
Board --> Square36
Board --> Square37

Board --> Square41
Board --> Square42
Board --> Square43
Board --> Square44
Board --> Square45
Board --> Square46
Board --> Square47

Board --> Square51
Board --> Square52
Board --> Square53
Board --> Square54
Board --> Square55
Board --> Square56
Board --> Square57

Board --> Square61
Board --> Square62
Board --> Square63
Board --> Square64
Board --> Square65
Board --> Square66
Board --> Square67

Square11 -[hidden]right-> Square12
Square12 -[hidden]right-> Square13
Square13 -[hidden]right-> Square14
Square14 -[hidden]right-> Square15
Square15 -[hidden]right-> Square16
Square16 -[hidden]right-> Square17

Square21 -[hidden]left-> Square22
Square22 -[hidden]left-> Square23
Square23 -[hidden]left-> Square24
Square24 -[hidden]left-> Square25
Square25 -[hidden]left-> Square26
Square26 -[hidden]left-> Square27

Square31 -[hidden]right-> Square32
Square32 -[hidden]right-> Square33
Square33 -[hidden]right-> Square34
Square34 -[hidden]right-> Square35
Square35 -[hidden]right-> Square36
Square36 -[hidden]right-> Square37

Square41 -[hidden]right-> Square42
Square42 -[hidden]right-> Square43
Square43 -[hidden]right-> Square44
Square44 -[hidden]right-> Square45
Square45 -[hidden]right-> Square46
Square46 -[hidden]right-> Square47

Square51 -[hidden]right-> Square52
Square52 -[hidden]right-> Square53
Square53 -[hidden]right-> Square54
Square54 -[hidden]right-> Square55
Square55 -[hidden]right-> Square56
Square56 -[hidden]right-> Square57

Square61 -[hidden]right-> Square62
Square62 -[hidden]right-> Square63
Square63 -[hidden]right-> Square64
Square64 -[hidden]right-> Square65
Square65 -[hidden]right-> Square66
Square66 -[hidden]right-> Square67

Square11 *-down-> Coordinate11
Square12 *-down-> Coordinate12
Square13 *-down-> Coordinate13
Square14 *-down-> Coordinate14
Square15 *-down-> Coordinate15
Square16 *-down-> Coordinate16
Square17 *-down-> Coordinate17

Square21 *-down-> Coordinate21
Square22 *-down-> Coordinate22
Square23 *-down-> Coordinate23
Square24 *-down-> Coordinate24
Square25 *-down-> Coordinate25
Square26 *-down-> Coordinate26
Square27 *-down-> Coordinate27

Square31 *-down-> Coordinate31
Square32 *-down-> Coordinate32
Square33 *-down-> Coordinate33
Square34 *-down-> Coordinate34
Square35 *-down-> Coordinate35
Square36 *-down-> Coordinate36
Square37 *-down-> Coordinate37

Square41 *-down-> Coordinate41
Square42 *-down-> Coordinate42
Square43 *-down-> Coordinate43
Square44 *-down-> Coordinate44
Square45 *-down-> Coordinate45
Square46 *-down-> Coordinate46
Square47 *-down-> Coordinate47

Square51 *-down-> Coordinate51
Square52 *-down-> Coordinate52
Square53 *-down-> Coordinate53
Square54 *-down-> Coordinate54
Square55 *-down-> Coordinate55
Square56 *-down-> Coordinate56
Square57 *-down-> Coordinate57

Square61 *-down-> Coordinate61
Square62 *-down-> Coordinate62
Square63 *-down-> Coordinate63
Square64 *-down-> Coordinate64
Square65 *-down-> Coordinate65
Square66 *-down-> Coordinate66
Square67 *-down-> Coordinate67


Square11 -[hidden]down-> Square21
Square12 -[hidden]down-> Square22
Square13 -[hidden]down-> Square23
Square14 -[hidden]down-> Square24
Square15 -[hidden]down-> Square25
Square16 -[hidden]down-> Square26
Square17 -[hidden]down-> Square27

Square21 -[hidden]down-> Square31
Square22 -[hidden]down-> Square32
Square23 -[hidden]down-> Square33
Square24 -[hidden]down-> Square34
Square25 -[hidden]down-> Square35
Square26 -[hidden]down-> Square36
Square27 -[hidden]down-> Square37


Square31 -[hidden]down-> Square41
Square32 -[hidden]down-> Square42
Square33 -[hidden]down-> Square43
Square34 -[hidden]down-> Square44
Square35 -[hidden]down-> Square45
Square36 -[hidden]down-> Square46
Square37 -[hidden]down-> Square47

Square41 -[hidden]down-> Square51
Square42 -[hidden]down-> Square52
Square43 -[hidden]down-> Square53
Square44 -[hidden]down-> Square54
Square45 -[hidden]down-> Square55
Square46 -[hidden]down-> Square56
Square47 -[hidden]down-> Square57

Square51 -[hidden]down-> Square61
Square52 -[hidden]down-> Square62
Square53 -[hidden]down-> Square63
Square54 -[hidden]down-> Square64
Square55 -[hidden]down-> Square65
Square56 -[hidden]down-> Square66
Square57 -[hidden]down-> Square67

@enduml