@startuml Namespaces
title Namespaces

namespace ConsoleApp #LightBlue { }
namespace GameViews #CadetBlue {}
namespace Controllers #DarkSlateBlue {}
namespace Models #RoyalBlue { }
namespace Types #Yellow { }

ConsoleApp .down.> Controllers
ConsoleApp .down.> GameViews
ConsoleApp .down.> Types

GameViews .down.> Types
GameViews .down.> Controllers

Controllers .down.> Models
Controllers .down.> Types

Models .down.> Types
@enduml