@startuml UseCasePlayView
title Use Case Play View

state IN_GAME
state OUT_GAME
state A as " "
state B as " "
state C as " "
state D as " "
state E as " "
state F as " "
state G as " "
state H as " "
state I as " "
state if1 <<choice>>
state if2 <<choice>>

[*] --> IN_GAME
IN_GAME --> A : Player requests Insert a Token
A --> B : System requests a coordinate
B --> C : Player enter the coordinate
C --> if1
    if1 --> D : [error]
    note on link
        Colunm is full
        Wrong Coordinate
    endnote
    D --> E : System shows Error Message
    E --> F 
    F --> [*] : System allows Play
if1 --> G 
G --> H : System shows update Board
H --> if2
    if2 --> F

if2 --> I : [IsFinished]
I --> OUT_GAME : System shows Result Message
OUT_GAME --> [*] : System allows Resume
@enduml