@startuml UseCasesContext
title Use Cases Context

state INITIAL
state IN_GAME
state OUT_GAME
state EXIT
state if <<choice>>
state if2 <<choice>>

[*] --> INITIAL
INITIAL --> IN_GAME : Start
IN_GAME --> if : Insert
    if --> IN_GAME
if --> OUT_GAME : [Finished]
OUT_GAME --> if2 : Resume
    if2 --> INITIAL : [continue]
if2 --> EXIT
EXIT --> [*]
@enduml