@startuml UseCaseViewContext
title Use Case View Start

state INITIAL
state IN_GAME
state A as " "
state B as " "

[*] --> INITIAL
INITIAL --> A : Player request Start a new game
A --> B : System displays board
B --> IN_GAME : System allows Play
IN_GAME --> [*] 
@enduml